# nginx with PHP5 for SES Dashboard

FROM ubuntu:14.04

MAINTAINER dan@asdsoftwaredesign.com

###############################################################################
# Updated the base ubuntu installation

RUN apt-get update 
RUN DEBIAN_FRONTEND=noninteractive apt-get -y upgrade
